### PR TITLE
fix(auth, web): fix currentUser being null when using emulator or named instance

### LINKED ISSUE #10200: 🐛 [firebase_auth] WEB - on restart current user is NULL (emulator suite)
## Bug report

You can use https://github.com/firebase/flutterfire/blob/master/packages/firebase_auth/firebase_auth/example/lib/main.dart

latest firebase tools, flutter version, running in OSX & chrome with connected emulators.

When you run in and authenticate -> you are moved to profile page.

If you now reload page, current user is NULL and authChanges trigger will only render NULL value.

Even if you change persistence to Local / IndexDB.

### PR DESCRIPTION
**Pull request by Lyokone**
## Description

I'm using localstorage when connecting to the emulator to save the emulator origin. 
On restart, if I detect an emulator origin in localstorage I directly connect to the emulator.

It allows for a good developer experience in debug mode; the only problem is that we cannot switch back from emulator to production during this Chrome session, and the developer has to relaunch the Flutter app completely to connect to a prod env. But I think it's the best behaviour. It allows Android, iOS and Web to finally have the same behaviour.

Message in console:
Screenshot 2023-03-06 at 09 57 28

## Related Issues

fixes #10200

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: packages/firebase_auth/firebase_auth/example/lib/auth.dart [hunk 1]
```diff
@@ -63,10 +62,10 @@ class AuthGate extends StatefulWidget {
   const AuthGate({Key? key}) : super(key: key);
 
   @override
-  State<StatefulWidget> createState() => _AuthGateState();
+  State<StatefulWidget> createState() => authGateState();
 }
 
-class _AuthGateState extends State<AuthGate> {
+class authGateState extends State<AuthGate> {
```
Comment (ahmednfwela) [inline packages/firebase_auth/firebase_auth/example/lib/auth.dart:68]: why is this in camel case?

Comment (Lyokone) [reply packages/firebase_auth/firebase_auth/example/lib/auth.dart]: Thanks, wasn't supposed to be changed 👍

**Review by russellwheatley — APPROVED** [review]

**Review by Ehesp — APPROVED** [review]
