### PR TITLE
fix(ios): fix clashing filenames between Auth and Firestore

### LINKED ISSUE #11720: 🐛 [firebase_auth] 'PigeonParser.h' file not found in iOS
## Bug report

**Describe the bug**
Error 'PigeonParser.h' file not found when compiling firebase_auth 4.11.0 on iOS.
It works on Android.

### Steps to reproduce

1. Compile any Flutter project for iOS and you get the error.

### Expected behavior

Compile and execute the app successful.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

octor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel unknown, 3.7.12, on macOS 13.6 22G120 darwin-arm64, locale es-ES)
    ! Flutter version 3.7.12 on channel unknown at /Users/marc/Library/Developer/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Unknown upstream repository.
      Reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Community Edition (version 2023.2.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

### PR DESCRIPTION
**Pull request by Lyokone**
## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

closes #11720 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by russellwheatley — APPROVED** [review]

File: packages/cloud_firestore/cloud_firestore/example/lib/main.dart [hunk 1]
```diff
@@ -10,7 +10,7 @@ import 'firebase_options.dart';
 
 /// Requires that a Firestore emulator is running locally.
 /// See https://firebase.flutter.dev/docs/firestore/usage#emulator-usage
-bool shouldUseFirestoreEmulator = true;
+bool shouldUseFirestoreEmulator = false;
```
Comment (exaby73) [inline packages/cloud_firestore/cloud_firestore/example/lib/main.dart:13]: What this change intentional?

**Review by exaby73 — APPROVED** [review]
LGTM

File: packages/cloud_firestore/cloud_firestore/example/lib/main.dart (hunk 1 above)
Comment (Lyokone) [reply packages/cloud_firestore/cloud_firestore/example/lib/main.dart:13]: Yes, it shouldn't have been changed in the first place 😅
