### PR TITLE
fix(database, web): change the interop to fix an issue with startAt/endAt/limitTo when compilating with dart2js in release mode

### LINKED ISSUE #9091: 🐛 [firebase_database] Crashes when querying with .equalTo(null).onValue - method not found: 'apply' on null
When I query something like this `db.ref().child('XXX').child(XXX).orderByChild('XXX').equalTo(null).onValue`  
I get the following error: `Uncaught TypeError: Cannot read properties of undefined (reading 'apply')`, `NoSuchMethodError: method not found: 'apply' on null`  

This exists after upgrading to the latest version `9.0.19`. If I revert my firebase packages to the previous versions, it works normally.  

Screenshot 2022-07-13 at 5 12 26 PM

P.S. I migrated from index.html initialization to the new in-dart FlutterFire CLI initialization, and removed all the firebase related code from the .html files.

### PR DESCRIPTION
**Pull request by Lyokone**
## Description

As discussed internally, there is an issue with dart2js compilation in release mode.
One of the workaround is to type those functions as Object.

## Related Issues

Fixes #9091

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: packages/firebase_database/firebase_database_web/lib/src/interop/database.dart [hunk 1]
```diff
@@ -455,12 +456,14 @@ class Query<T extends database_interop.QueryJsImpl> extends JsObjectWrapper<T> {
...
   S? _createQueryConstraint<S>(
-      Function method, List<dynamic>? /*list of primitive value */ args) {
+      Object method, List<dynamic>? /*list of primitive value */ args) {
     if (args == null) {
       throw ArgumentError('Please provide "args" parameter.');
     }
     var params = args.map(jsify).toList();
-    return callMethod(method, 'apply', jsify([null, params]));
+    print(method);
+    print(params);
```
Comment (russellwheatley) [inline packages/firebase_database/firebase_database_web/lib/src/interop/database.dart:465]:
```suggestion

```

**Review by russellwheatley — CHANGES_REQUESTED** [review]

File: packages/firebase_database/firebase_database_web/lib/src/interop/database.dart (hunk 1 above)
Comment (Salakar) [inline packages/firebase_database/firebase_database_web/lib/src/interop/database.dart:465]:
```suggestion
```

Comment (russellwheatley) [reply packages/firebase_database/firebase_database_web/lib/src/interop/database.dart:465]: snap!

**Review by Salakar — CHANGES_REQUESTED** [review]
Some prints

File: packages/firebase_database/firebase_database_web/lib/src/interop/database.dart (hunk 1 above)
Comment (Lyokone) [reply packages/firebase_database/firebase_database_web/lib/src/interop/database.dart]: Oops a bit quick on this one 😓

**Review by Salakar — APPROVED** [review]

**Review by russellwheatley — APPROVED** [review]
