### PR TITLE
fix(firestore, ios): fix crash that could occur when using transactions

### LINKED ISSUE #9527: Confirmed crash / potential memory leak / logic error in transaction error handler
We were troubleshooting a crash with transaction handling and stumbled upon this line (although might be unrelated).

https://github.com/firebase/flutterfire/blob/49921a4362c5965d2efeed17eb73775302007ea8/packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestorePlugin.m#L348

See inserted `//` comments for details:

```
    FIRTransaction *transaction = self->_transactions[transactionId];

    NSError *error = [[NSError alloc] init]; // <--- Memory allocated here
    FIRDocumentSnapshot *snapshot = [transaction getDocument:document error:&error]; // <--- pointer is immediately overwritten

    if (error != nil) { // <--- If [FIRTransaction getDocument] has any execution path where it does not set error pointer to nil, this will result in a false error because we would not be nil due to initial alloc+init on the second line.
      result.error(nil, nil, nil, error);
    } else if (snapshot != nil) {
      result.success(snapshot);
    } else {
      result.success(nil);
    }
```
It appears that FIRTransaction.getDocument has error as `__autoreleasing`

Apple's official documentation examples show that error should not be initialized:
```


NSError *error;
--
BOOL OK = [myObject performOperationWithError:&error];
if (!OK) {
// Report the error.
// ...

```

```
-(BOOL)performOperationWithError:(NSError * __autoreleasing *)error;

```

Source: https://developer.apple.com/library/archive/releasenotes/ObjectiveC/RN-TransitioningToARC/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011226-CH1-SW4

### PR DESCRIPTION
**Pull request by Lyokone**
## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

closes #9527 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestorePlugin.m [hunk 1]
```diff
@@ -371,6 +371,13 @@ - (void)transactionGet:(id)arguments withMethodCallResult:(FLTFirebaseMethodCall
 
     FIRTransaction *transaction = self->_transactions[transactionId];
 
+    if (transaction == nil) {
+      result.error(@"missing-transaction",
+                   @"An error occurred while getting the native transaction. "
+                   @"It could be caused by a timeout in a precedent transaction operation.",
```
Comment (russellwheatley) [inline packages/cloud_firestore/cloud_firestore/ios/Classes/FLTFirebaseFirestorePlugin.m:377]: >
```suggestion
                   @"It could be caused by a timeout in a preceding transaction operation.",
```

**Review by russellwheatley — APPROVED** [review]

**Review by pr-Mais — APPROVED** [review]
