### PR TITLE
fix(cloud_firestore): propagate COLLECTION_GROUP_ASC index error message

### LINKED ISSUE #10105: 🐛 [cloud_firestore] url to firebase console where collection group index is built isn't propagated
## Bug report

When using `collectionGroup` queries without a necessary index, we get a `failed-precondition` error without an url to firebase console where an index could be built.

### Steps to reproduce

Run the following query on a collection group that doesn't have a proper index built

```
FirebaseFirestore.instance
      .collectionGroup('sub')
      .where('id', isEqualTo: 0)
      .get(const GetOptions(source: Source.server))
      .then((value) => print(value));
```

### Expected behaviour

An error with a link to firebase console is thrown

### Actual behaviour

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [cloud_firestore/failed-precondition] Operation was rejected because the system is not in a state required for the operation's execution. If performing a query, ensure it has been indexed via the Firebase console.
```

### PR DESCRIPTION
**Pull request by lesnitsky**
## Related Issues

Closes #10105

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: packages/_flutterfire_internals/lib/src/exception.dart [hunk 1]
```diff
@@ -47,7 +47,9 @@ FirebaseException platformExceptionToFirebaseException(
 
   if (details != null) {
     code = (details['code'] as String?) ?? code;
-    message = (details['message'] as String?) ?? message;
+    message = (details['nativeErrorMessage'] as String?) ??
```
Comment (Lyokone) [inline packages/_flutterfire_internals/lib/src/exception.dart:50]: Is it going to change a lot of error messages? Should another field like "nativeErrorMessage" in the FirebaseExeption?

**Review by russellwheatley — APPROVED** [review]
