### PR TITLE
fix(auth): fix an issue where unenroll would not throw a FirebaseException

### LINKED ISSUE #10543: 🐛 [firebase_auth] throw PlatformException when unenroll a multiFactor
## Bug report

**Describe the bug**
When call firebaseAuth.currentUser!.multiFactor.unenroll it throws PlatformException. I am not able to catch error in dart side then give user information about that.

### Steps to reproduce

1. Call `firebaseAuth.currentUser!.multiFactor.unenroll(multiFactorInfo:phoneMultiFactorInfo);` without reauthenticate.
2. It throws `PlatformException(FirebaseAuthRecentLoginRequiredException, com.google.firebase.auth.FirebaseAuthRecentLoginRequiredException: This operation is sensitive and requires recent authentication. Log in again before retrying this request., Cause: null, Stacktrace: com.google.firebase.auth.FirebaseAuthRecentLoginRequiredException: This operation is sensitive and requires recent authentication. Log in again before retrying this request.`

### Expected behavior

I should able to catch error like this.
```
try {
  await firebaseAuth.currentUser!.multiFactor.unenroll(multiFactorInfo:phoneMultiFactorInfo);
} on FirebaseAuthRecentLoginRequiredException catch (e) {
  // Give user corresponding info about error
}
```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 3.3.7, on Microsoft Windows [version 10.0.19045.2604], locale zh-TW)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)                         
[√] Chrome - develop for the web                                                                         
[X] Visual Studio - develop for Windows                                                                  
    X Visual Studio not installed; this is necessary for Windows development.                            
      Download at https://visualstudio.microsoft.com/downloads/.                                         
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.3)                                                                      
[√] VS Code (version 1.75.1)                                                                             
[√] Connected device (6 available)                                                                       
[√] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
firebase_core 2.7.0 
firebase_auth 4.2.9
```

</details>

---

### PR DESCRIPTION
**Pull request by Lyokone**
## Description

By returning directly the Future and not await it, the error will never be catched by firebase.

## Related Issues

closes #10543 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: packages/firebase_auth/firebase_auth/lib/src/multi_factor.dart [hunk 1]
```diff
@@ -33,6 +33,11 @@ class MultiFactor {
   /// [multiFactorInfo] is the [MultiFactorInfo] of the second factor to unenroll.
   /// Only one of [factorUid] or [multiFactorInfo] should be provided.
   Future<void> unenroll({String? factorUid, MultiFactorInfo? multiFactorInfo}) {
+    assert(
+      (factorUid != null && multiFactorInfo == null) ||
+          (factorUid == null && multiFactorInfo != null),
+      'Exactly one of factorUid or multiFactorInfo must be provided',
```
Comment (russellwheatley) [inline packages/firebase_auth/firebase_auth/lib/src/multi_factor.dart:39]:
```suggestion
      'Exactly one of `factorUid` or `multiFactorInfo` must be provided',
```

File: tests/integration_test/firebase_auth/firebase_auth_multi_factor_e2e_test.dart [hunk 2]
```diff
@@ -170,6 +170,118 @@ void main() {
...
+            } catch (e) {
+              expect(e, isA<FirebaseAuthException>());
+            }
+
+            final enrolledFactorsAfter = await multiFactor.getEnrolledFactors();
+
+            // Assertions
+            expect(enrolledFactorsAfter.length, 1);
+          },
+          skip: kIsWeb || defaultTargetPlatform != TargetPlatform.android,
```
Comment (russellwheatley) [inline tests/integration_test/firebase_auth/firebase_auth_multi_factor_e2e_test.dart:282]: Should this also be true for iOS?

**Review by russellwheatley — CHANGES_REQUESTED** [review]

File: tests/integration_test/firebase_auth/firebase_auth_multi_factor_e2e_test.dart (hunk 2 above)
Comment (Lyokone) [reply tests/integration_test/firebase_auth/firebase_auth_multi_factor_e2e_test.dart:282]: This test (from which this one is copied) was already skipped for iOS. We cannot get the multifactor to work on iOS in CI because it tries to verify for Recaptcha and fails :/

**Review by rrousselGit — APPROVED** [review]

File: tests/integration_test/firebase_auth/firebase_auth_multi_factor_e2e_test.dart (hunk 2 above)
Comment (russellwheatley) [reply tests/integration_test/firebase_auth/firebase_auth_multi_factor_e2e_test.dart:282]: Perhaps leave a note explaining such 😄

**Review by russellwheatley — APPROVED** [review]
After leaving comment on test - LGTM

File: tests/integration_test/firebase_auth/firebase_auth_multi_factor_e2e_test.dart (hunk 2 above)
Comment (Lyokone) [reply tests/integration_test/firebase_auth/firebase_auth_multi_factor_e2e_test.dart:282]: Good call I'll add that :)
