### PR TITLE
fix(firestore, web): update `setSettings` to allow usage of a up-to-date persistence on web

### LINKED ISSUE #12034: 🐛 [cloud_firestore] Use of deprecated enableMultiTabIndexedDbPersistence() API on Web
## Bug report

**Describe the bug**
When enabling offline persistence for Cloud Firestore on web (as shown in the docs), Firestore gives a warning about using a deprecated API. 

### Steps to reproduce

1. After confirming the running platform is web, run the following code in an async context (assuming `db` is an instance of `FirebaseFirestore`:
```dart
await db.enablePersistence(const PersistenceSettings(synchronizeTabs: true));
```
4. In the browser console, you'll find a warning about using a deprecated API:
```
@firebase/firestore: Firestore (10.7.0): enableMultiTabIndexedDbPersistence() will be deprecated in the future, you can use FirestoreSettings.cache instead.
```

### Expected behavior

The FlutterFire `cloud_firestore` plugin uses the new `FirestoreSettings.cache` API and thus the Firestore JS API does not log a warning to the console.

### Sample project

Assumes correct imports.

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
 if (kIsWeb) {
      await db.enablePersistence(const PersistenceSettings(synchronizeTabs: true));
  } 
}
```

---

## Additional context

Using latest version of `cloud_firestore` plugin (4.13.6) at time of issue submission.

Use of deprecated API introduced in #10024.

It seems the new way to do this in the new JS API is to use the following when initializing Firestore:

```js
  initializeFirestore(app, {
    localCache: persistentLocalCache(/*settings*/ { tabManager: persistentMultipleTabManager() }),
  });
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.2, on Debian GNU/Linux 12 (bookworm) 6.2.0-1018-azure, locale
    en_US.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✗] Linux toolchain - develop for Linux desktop
    ✗ clang++ is required for Linux development.
      It is likely available from your distribution (e.g.: apt install clang), or can be downloaded from
      https://releases.llvm.org/
    ✗ CMake is required for Linux development.
      It is likely available from your distribution (e.g.: apt install cmake), or can be downloaded from
      https://cmake.org/download/
    ✗ ninja is required for Linux development.
      It is likely available from your distribution (e.g.: apt install ninja-build), or can be downloaded
      from https://github.com/ninja-build/ninja/releases
    ✗ pkg-config is required for Linux development.
      It is likely available from your distribution (e.g.: apt install pkg-config), or can be downloaded
      from https://www.freedesktop.org/wiki/Software/pkg-config/
[!] Android Studio (not installed)
[✓] Connected device (1 available)
[✓] Network resources
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 3.2.2
Flutter SDK 3.16.2
<my_app_name> 1.0.0+1

dependencies:
- cloud_firestore 4.13.6 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth 4.15.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 2.24.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 3.4.8 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_performance 0.9.3+8 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta vector_math web sky_engine]
- go_router 12.1.3 [collection flutter flutter_web_plugins logging meta]
- intl 0.19.0 [clock meta path]
- loading_animation_widget 1.2.0+4 [flutter]
- material_text_fields 1.0.3 [flutter]

dev dependencies:
- flutter_lints 3.0.1 [lints]
- flutter_test 0.0.0 [flutter test_api matcher path fake_async clock stack_trace vector_math async boolean_selector characters collection material_color_utilities meta source_span stream_channel string_scanner term_glyph web]

transitive dependencies:
- _flutterfire_internals 1.3.16 [collection firebase_core firebase_core_platform_interface flutter meta]
- async 2.11.0 [collection meta]
- boolean_selector 2.1.1 [source_span string_scanner]
- characters 1.3.0
- clock 1.1.1
- cloud_firestore_platform_interface 6.0.10 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 3.8.10 [_flutterfire_internals cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.18.0
- fake_async 1.3.1 [clock collection]
- firebase_auth_platform_interface 7.0.9 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 5.8.12 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser js meta]
- firebase_core_platform_interface 5.0.0 [collection flutter flutter_test meta plugin_platform_interface]
- firebase_core_web 2.10.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.6.16 [_flutterfire_internals collection firebase_core flutter meta plugin_platform_interface]
- firebase_performance_platform_interface 0.1.4+16 [_flutterfire_internals firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.1.4+16 [_flutterfire_internals firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins js]
- flutter_web_plugins 0.0.0 [flutter characters collection material_color_utilities meta vector_math web]
- http_parser 4.0.2 [collection source_span string_scanner typed_data]
- js 0.6.7 [meta]
- lints 3.0.0
- logging 1.2.0
- matcher 0.12.16 [async meta stack_trace term_glyph test_api]
- material_color_utilities 0.5.0 [collection]
- meta 1.10.0
- path 1.8.3
- plugin_platform_interface 2.1.7 [meta]
- sky_engine 0.0.99
- source_span 1.10.0 [collection path term_glyph]
- stack_trace 1.11.1 [path]
- stream_channel 2.1.2 [async]
- string_scanner 1.2.0 [source_span]
- term_glyph 1.2.1
- test_api 0.6.1 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph]
- typed_data 1.3.2 [collection]
- vector_math 2.1.4
- web 0.3.0
```

</details>

---

### PR DESCRIPTION
**Pull request by Lyokone**
## Description

see title 

## Related Issues

fixes #12034

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by exaby73 — APPROVED** [review]

File: packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart [hunk 1]
```diff
@@ -160,6 +163,34 @@ external QueryConstraintJsImpl orderBy(
...
+
+@JS()
+external PersistentSingleTabManager persistentSingleTabManager(
+  PersistentSingleTabManagerSettings? settings,
+);
+
+@JS()
+external PersistentMultipleTabManager persistentMultipleTabManager(
+  PersistentSingleTabManagerSettings? settings,
+);
```
Comment (russellwheatley) [inline packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart:192]: Is the aim to allow these in the future? (along with `memoryEagerGarbageCollector()` & `memoryLruGarbageCollector()`)

**Review by russellwheatley — APPROVED** [review]

File: packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart (hunk 1 above)
Comment (Lyokone) [reply packages/cloud_firestore/cloud_firestore_web/lib/src/interop/firestore_interop.dart:192]: Yes we probably need to refactor the front facing API to expose those APIs. I have to draft the API Review

File: packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart [hunk 2]
```diff
@@ -129,26 +129,28 @@ class FirebaseFirestoreWeb extends FirebaseFirestorePlatform {
...
-      // https://github.com/firebase/firebase-js-sdk/blob/e67affba53a53d28492587b2f60521a00166db60/packages/firestore/src/local/lru_garbage_collector.ts#L175
-      cacheSizeBytes = -1;
+    // Union type MemoryLocalCache | PersistentLocalCache
+    dynamic localCache;
+    final persistenceEnabled = settings.persistenceEnabled;
+    if (persistenceEnabled == null || persistenceEnabled == false) {
+      localCache = firestore_interop.memoryLocalCache(null);
     } else {
-      cacheSizeBytes = settings.cacheSizeBytes;
+      localCache = firestore_interop
```
Comment (dvoloshyn) [inline packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart:138]: After deprecation of `enablePersistence` we no longer have an API to specify multiple tab behavior on Web. So, which tab manager will be used by default when I set `persistenceEnabled: true` on Web?
