### PR TITLE
fix(firestore): supports Iterable in queries instead of List

### LINKED ISSUE #10407: 🐛 [Firestore] where APIs should take an Iterable instead of a List
## Bug report

The `where` method  for Firestore takes a `List` value,  but for maximum compatibility that should probably be an `Iterable`.

---

## Additional context

See this [question on Stack Overflow](https://stackoverflow.com/q/75392186/209103)

### PR DESCRIPTION
**Pull request by Lyokone**
## Description

We should support Iterable instead of List to make the API easier for the end user.

## Related Issues

closes #10407 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Review by russellwheatley — APPROVED** [review]

File: packages/cloud_firestore/cloud_firestore/lib/src/query.dart [hunk 1]
```diff
@@ -703,19 +703,19 @@ class _JsonQuery implements Query<Map<String, dynamic>> {
...
           isNotIn(operator)) {
         assert(
-          value is List,
+          value is Iterable,
           "A non-empty [List] is required for '$operator' filters.",
         );
         assert(
-          (value as List).length <= 10,
+          (value as Iterable).length <= 10,
           "'$operator' filters support a maximum of 10 elements in the value [List].",
```
Comment (pr-Mais) [inline packages/cloud_firestore/cloud_firestore/lib/src/query.dart:711]: Should this be `[Iterable]` instead of `[List]`?

**Review by pr-Mais — APPROVED** [review]
