### PR TITLE
fix(firestore, ios): fix freeze when doing a get in transactions when auth is also installed

### LINKED ISSUE #11755: 🐛 [cloud_firestore] Only iOS does not return a response for transaction get.
## Bug report

Only iOS does not return a response for transaction get. Android returns correctly.

## Additional context

cloud_firestore: 4.11.0 => NG, No response.
cloud_firestore: 4.9.3 => OK, Correct.

```dart
Future<void> func() async {
  await FirebaseFirestore.instance.runTransaction<void>((transaction) async {
    final ref = ...;
    final res = await transaction.get(ref); // no response and stop process.
  });
}
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.8, on macOS 13.5.2 22G91 darwin-arm64, locale
    ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (6 available)
    ! Error: Browsing on the local area network for Apple Vision. Ensure the
      device is unlocked and attached with a cable or associated with the same
      local area network as this Mac. (code -27)
[✓] Network resources
```

</details>

---

### PR DESCRIPTION
**Pull request by Lyokone**
## Description

While migrating to pigeon, some dispatching code was removed by error. 

## Related Issues

closes #11755 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [X] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: packages/cloud_firestore/cloud_firestore/example/integration_test/transaction_e2e.dart [hunk 1]
```diff
@@ -424,6 +425,33 @@ void runTransactionTests() {
             await documentReference2.get();
         expect(snapshot2.exists, isFalse);
       });
+
+      testWidgets('should not fail to get if user is authentified', (_) async {
```
Comment (russellwheatley) [inline packages/cloud_firestore/cloud_firestore/example/integration_test/transaction_e2e.dart:429]:
```suggestion
      testWidgets('should not fail to complete transaction if user is authenticated', (_) async {
```

**Review by exaby73 — APPROVED** [review]

**Review by russellwheatley — APPROVED** [review]
LGTM - once green 👍

File: packages/cloud_firestore/cloud_firestore/example/integration_test/transaction_e2e.dart (hunk 1 above)
Comment (Lyokone) [reply packages/cloud_firestore/cloud_firestore/example/integration_test/transaction_e2e.dart]: Applied :)
