### PR TITLE
fix(messaging, iOS): refactor notification handling in scene delegate methods

### LINKED ISSUE #17854: [firebase_messaging]: getInitialMessage hangs indefinitely
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Which plugins are affected?

Messaging

### Which platforms are affected?

iOS

### Description

When calling FirebaseMessaging.instance.getInitialMessage the call hangs indefinitely

### Reproducing the issue

Call FirebaseMessaging.instance.getInitialMessage() with version ^16.0.4 and flutter version 3.38.1

### Firebase Core version

4.2.1

### Flutter Version

3.38.1

### Relevant Log Output

```shell

```

### Flutter dependencies

<details>
<summary>Expand <code>Flutter dependencies</code> snippet</summary>
<br>

```yaml

  cupertino_icons: ^1.0.8
  animated_widgets: ^1.1.0
  firebase_analytics: ^12.0.4
  popover: ^0.3.1
  rxdart: ^0.28.0
  http: ^1.5.0
  country_code_picker: ^3.0.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  another_flushbar: ^1.12.30
  flutter_facebook_auth: ^7.1.2
  flutter_spinkit: ^5.2.1
  loading_animations: ^2.2.0
  retrofit: ^4.7.1
  json_annotation:
  json_serializable: ^6.10.0
  dio: ^5.9.0
  dio_http_cache_lts: ^0.4.1
  connectivity_plus: ^6.1.5
  shared_preferences: ^2.0.5
  pin_code_fields: ^8.0.1
  phone_numbers_parser: ^9.0.3
  image_picker: ^1.2.0
  image_cropper: ^9.1.0
  firebase_storage: ^13.0.4
  intl: ^0.18.1
  country_state_city_picker: ^1.2.8
  awesome_dialog: ^3.2.1
  adaptive_action_sheet: ^2.0.4
  file_picker: ^10.3.2
  fast_contacts: ^4.0.0
  permission_handler: ^12.0.1
  flutter_countdown_timer: ^4.1.0
  chewie: ^1.13.0
  timeago: ^3.7.1
  video_player: ^2.10.0
  confetti: ^0.8.0
  path_provider: ^2.1.4
  get_time_ago:
  pull_to_refresh: ^2.0.0
  omni_datetime_picker: ^2.0.5
  flutter_tags_x: ^1.1.0
  grouped_list:
  emoji_picker_flutter: ^4.3.0
  carousel_slider: ^5.1.1
  in_app_purchase: ^3.2.3
  in_app_purchase_storekit: 0.4.4
  cloud_firestore: ^6.0.3
  # firebase
#  video_compress: ^3.1.0
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.7
  image: ^4.3.0
#  video_trimmer: ^2.1.0
  uuid: ^4.4.2
  googleapis_auth: ^1.6.0
  background_downloader: ^9.2.6
  googleapis: ^11.2.0
  flutter_local_notifications: ^19.5.0
  gcloud: ^0.8.5
  mime_type: ^1.0.0
  percent_indicator: ^4.2.2
  hive_ce: ^2.12.0
  hive_ce_flutter: ^2.3.2
  page_transition: ^2.0.4
  modal_progress_hud_nsn: ^0.5.1
  flutter_typeahead: ^5.2.0
  image_cropping: ^0.0.9
  firebase_messaging: ^16.0.4
  webview_flutter: ^4.8.0
  marquee: ^2.3.0
  share_plus: ^12.0.1
  nb_utils: ^7.1.7+2
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.15.0
  # full is for android
#  ffmpeg_kit_flutter_full: ^6.0.3-LTS
#  ffmpeg_kit_flutter_full_gpl: ^6.0.3-LTS
  flutter_svg_provider: ^1.0.7
#  agora_rtc_engine: ^6.3.2
  google_sign_in: ^7.1.1
#  firebase_app_check: ^0.3.1+3
  firebase_crashlytics: ^5.0.4
  firebase_in_app_messaging: ^0.9.0+4
  watcher: ^1.1.0
  memory_info: ^0.0.3
  go_router: ^17.0.0
  google_fonts: ^6.3.0
  sign_in_with_apple: ^7.0.1
  webview_flutter_plus: ^0.4.5
  url_launcher: ^6.3.2
  audioplayers: ^6.5.0
  dotted_border: ^3.1.0
#  tflite_flutter_helper: ^0.3.1
  tflite_flutter: ^0.11.0
#  tflite_flutter_helper_plus: ^0.0.2
#  tflite_flutter_helper_plus: ^0.0.2
#  agora_rtc_engine: 5.2.0
#  shelf: ^1.4.1
#  shelf_static: ^1.1.2
#  shelf_cors_headers: ^0.1.5
  flutter_inappwebview: ^6.0.0
  package_info_plus: ^8.0.2
  sliver_tools: ^0.2.12
  in_app_review: ^2.0.10
  cupertino_back_gesture: ^0.1.0
  crypto: ^3.0.6
  mime: any
  path: any
  in_app_purchase_android: any
  upgrader: ^11.5.0
  video_compress: ^3.1.4
  tutorial_coach_mark: ^1.3.3
  video_player_android: ^2.7.17
#  media_kit_libs_android_video: any
#  video_player_media_kit: ^1.0.5
  device_info_plus: ^11.3.0
  youtube_player_flutter: ^9.1.1
  better_player_plus: ^1.0.8
  flutter_video_caching: ^0.4.4

```

</details>

### Additional context and comments

_No response_

### PR DESCRIPTION
**Pull request by SelaseKay**
## Description
On `firebase_messaging` to support `UISceneDelegates`, the various callbacks(`onMessage` and `onBackgroundMessage`) weren't getting invoked for background/foreground notifications. This PR resolves this issue. 

The PR is still in progress to address the issue where `getInitialMessage` always returns null in relation to the migration. 

## Related Issues
Fixes https://github.com/firebase/flutterfire/issues/17854

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/flutter/flutter/issues). Indicate, which of these issues are resolved or fixed by this PR. Note that you'll have to prefix the issue numbers with flutter/flutter#.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/main/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: packages/firebase_messaging/firebase_messaging/example/ios/Runner/AppDelegate.m [hunk 1]
```diff
@@ -5,9 +5,13 @@ @implementation AppDelegate
 
 - (BOOL)application:(UIApplication *)application
     didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
-  [GeneratedPluginRegistrant registerWithRegistry:self];
+  // [GeneratedPluginRegistrant registerWithRegistry:self];
```
Comment (MichaelVerdon) [inline packages/firebase_messaging/firebase_messaging/example/ios/Runner/AppDelegate.m]: Is this comment meant to be here?

**Review by MichaelVerdon — APPROVED** [review]

File: packages/firebase_messaging/firebase_messaging/example/ios/Runner/AppDelegate.m (hunk 1 above)
Comment (SelaseKay) [reply packages/firebase_messaging/firebase_messaging/example/ios/Runner/AppDelegate.m]: Good catch. It's not supposed to be there.

**Review by Lyokone — APPROVED** [review]
