### PR TITLE
fix(ui_auth): fix OAuth providers on RegisterScreen

### LINKED ISSUE #9064: [flutterfire_ui] Social media failing on RegisterScreen
## Bug report

This was previously reported in https://github.com/firebase/flutterfire/issues/8219

I don't have much to add to the bug beyond what was initially reported. 

### Steps to reproduce

I experienced this while working with Google Sign In, but it should how true to anything using the AuthFlow class.
1. Download the [FlutterFire UI example](https://github.com/firebase/flutterfire/tree/master/packages/flutterfire_ui/example).
2. Update project with the appropriate Firebase/Google Sign In configurations
3. Sign In works as expected, Register Shows "An unknown error occurred"

### Expected behavior

This depends on how we want to semantically consider things. On one hand, you could consider that `AuthAction.signIn` and `AuthAction.signUp` should be the same thing in these cases because there is no difference in implementation.

On the other hand, you could argue that they are different. In that case, either we could continue to block signup, or we could implement a signup. If we continue to block signup, that necessitates a change to the RegisterScreen - it shouldn't present the social options if they're always going to error.

### Sample project

https://github.com/firebase/flutterfire/tree/master/packages/flutterfire_ui/example

### PR DESCRIPTION
**Pull request by lesnitsky**
## Related Issues

Closes #9064

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/firebase/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: packages/firebase_ui_auth/lib/src/providers/auth_provider.dart [hunk 1]
```diff
@@ -168,13 +168,14 @@ abstract class AuthProvider<T extends AuthListener, K extends AuthCredential> {
         linkWithCredential(credential);
         break;
       case AuthAction.signIn:
+      // Only email provider has a different action for sing in and sign up
```
Comment (Lyokone) [inline packages/firebase_ui_auth/lib/src/providers/auth_provider.dart:171]:
```suggestion
      // Only email provider has a different action for sign in and sign up
```

**Review by Lyokone — APPROVED** [review]

**Review by russellwheatley — APPROVED** [review]
